import { Metadata } from "next";
import type { AppType } from "next/app";
import { Inter } from "next/font/google";
import { trpc } from "../utils/trpc";
import "../globals.css";

// This wraps trpc around root component
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Collab dev team",
  description: "Generated by create next app",
};

const App: AppType = ({ Component, pageProps }) => {
  return <Component className={inter.className} {...pageProps} />;
};

export default trpc.withTRPC(App);
